@isTest
private class dialogikaDeInfportSchemaPbV1Test
{
    
    private static testMethod void testSchema()
    {
        dialogikaDeInfportSchemaPbV1.tS_ProviderSpecific ps = new dialogikaDeInfportSchemaPbV1.tS_ProviderSpecific();
        dialogikaDeInfportSchemaPbV1.tPortEntryRequest per = new dialogikaDeInfportSchemaPbV1.tPortEntryRequest();
        dialogikaDeInfportSchemaPbV1.tR_PhoneNumber pn = new dialogikaDeInfportSchemaPbV1.tR_PhoneNumber();
        dialogikaDeInfportSchemaPbV1.tGetCurrentByPhoneNumberResponse gcbpnr = new dialogikaDeInfportSchemaPbV1.tGetCurrentByPhoneNumberResponse();
        dialogikaDeInfportSchemaPbV1.tK_Correspondence c = new dialogikaDeInfportSchemaPbV1.tK_Correspondence();
        dialogikaDeInfportSchemaPbV1.tResponse r = new dialogikaDeInfportSchemaPbV1.tResponse();
        dialogikaDeInfportSchemaPbV1.tSelectDateResellerRequest sdrr = new dialogikaDeInfportSchemaPbV1.tSelectDateResellerRequest();
        dialogikaDeInfportSchemaPbV1.tCreateEntryRequest cer = new dialogikaDeInfportSchemaPbV1.tCreateEntryRequest();
        dialogikaDeInfportSchemaPbV1.tSelectRequest sr = new dialogikaDeInfportSchemaPbV1.tSelectRequest();
        dialogikaDeInfportSchemaPbV1.tA_Order ord = new dialogikaDeInfportSchemaPbV1.tA_Order();
        dialogikaDeInfportSchemaPbV1.tE_Entry eEntry = new dialogikaDeInfportSchemaPbV1.tE_Entry();
        dialogikaDeInfportSchemaPbV1.tPortEntryResponse per1 = new dialogikaDeInfportSchemaPbV1.tPortEntryResponse();
        dialogikaDeInfportSchemaPbV1.tAddEntryRequest aer = new dialogikaDeInfportSchemaPbV1.tAddEntryRequest();
        dialogikaDeInfportSchemaPbV1.tPbEntry pEntry = new dialogikaDeInfportSchemaPbV1.tPbEntry();
        dialogikaDeInfportSchemaPbV1.tDeleteEntryResponse der = new dialogikaDeInfportSchemaPbV1.tDeleteEntryResponse();
        dialogikaDeInfportSchemaPbV1.tAddEntryResponse tAer = new dialogikaDeInfportSchemaPbV1.tAddEntryResponse();
        dialogikaDeInfportSchemaPbV1.tUpdateEntryResponse uer = new dialogikaDeInfportSchemaPbV1.tUpdateEntryResponse();
        dialogikaDeInfportSchemaPbV1.tUpdateEntryRequest uEReq = new dialogikaDeInfportSchemaPbV1.tUpdateEntryRequest();
        dialogikaDeInfportSchemaPbV1.tSelectResponse tSR = new dialogikaDeInfportSchemaPbV1.tSelectResponse();
        dialogikaDeInfportSchemaPbV1.tCreateEntryResponse tCER = new dialogikaDeInfportSchemaPbV1.tCreateEntryResponse();
        dialogikaDeInfportSchemaPbV1.tDeleteEntryRequest tDER = new dialogikaDeInfportSchemaPbV1.tDeleteEntryRequest();
        dialogikaDeInfportSchemaPbV1.tGetCurrentByPhoneNumberRequest tGCBPNR = new dialogikaDeInfportSchemaPbV1.tGetCurrentByPhoneNumberRequest();
        
    }
}