/*******************************************************************************************************************************************
* File Name     :  LG_CreateDataFromDWHFeedSchedulable
* Description   :  This is a schedulable class that runs the batch class  LG_CreateDataFromDWHFeedBatch.

* @author       :   Shreyas Ringe
* Modification Log
===================================================================================================
* Ver.    Date          Author              Modification
---------------------------------------------------------------------------------------------------
* 1.0      2nd-Feb-16    Shreyas             Created the class for release R1*

********************************************************************************************************************************************/
public class LG_CreateDataFromDWHFeedSchedulable {
    public void method(){}
    /*

    public void execute(SchedulableContext sc) {
        LG_CreateDataFromDWHFeedBatch proceedFeed = new LG_CreateDataFromDWHFeedBatch(); 
        if(!Test.isRunningTest()){ 
            database.executebatch(proceedFeed,1);
        }*/
    }