/*******************************************************************
* Date : 6-Dec-2017
* Name : LG_ObserverPcTest
* Description : Test class for LG_ObserverPc class
*******************************************************************/ 

@isTest
public class LG_ObserverPcTest {
    public static testmethod void impltest(){
        test.startTest();
        LG_ObserverPc obs=new LG_ObserverPc();
        
        test.stopTest();
        
    }

}