@isTest
public class pkwsWsbnkWsdlTypesTest {
    
    public static testmethod void wsdltest(){
        
        pkwsWsbnkWsdlTypes.WsbnkBankrectypeBase bas=new pkwsWsbnkWsdlTypes.WsbnkBankrectypeBase();
        pkwsWsbnkWsdlTypes.WsbnkBankrectypeUser user=new pkwsWsbnkWsdlTypes.WsbnkBankrectypeUser();
        pkwsWsbnkWsdlTypes.WsbnkBankrectypeUserArray arr=new pkwsWsbnkWsdlTypes.WsbnkBankrectypeUserArray();
        
    }

}