UM_AccountNumber__c,UM_ArticleNumber__c,UM_CustomerName__c,UM_Description__c,UM_Enddate__c,UM_ExportType__c,UM_HeadOfficeNumber__c,UM_Interval__c,UM_Quantity__c,UM_ShippingDate__c,UM_Startdate__c,UM_Status__c,UM_SubscriberID__c,UM_TotalPrice__c,UM_Type__c,UM_UnitPrice__c,UM_VoiceworksAccountID__c,UM_VoiceWorksObjectId__c,UM_Country__c,UM_ProcessLater__c
6100001497|11430130,12472,Voiceworks GmbH - OnePhone Test Company I,"{""Extension"": ""224"", ""Name"": ""Josip"",""StoreOrderNumber"":
""201707051002""}",,Billing,,1,1,,2017-07-14,New,,,Feed,,45810,,Germany,TRUE
